# -*- coding: utf-8 -*-
"""Numpy_starter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fj3S87PRjXh3rdrE2mtjCiYGy4j2FUmV
"""

import numpy as np
a = np.array([1,2,3])
print(a)